version: 2.0.0.{build}
image: Visual Studio 2022
init:
- cmd: '"C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat"'
install:
- cmd: nmake restore
build_script:
- cmd: >-
    nmake

    nmake deploy
artifacts:
- path: Koturn.NativeCode-netstandard2.0.zip
  name: .NET Standard 2.0 binary
- path: Koturn.NativeCode-net8.0.zip
  name: .NET Standard 8.0 binary
- path: Koturn.NativeCode-net9.0.zip
  name: .NET Standard 9.0 binary
